"""Export step: business-analysis tables, significance tests and the data-quality report.
Everything is read from Postgres, so the files always reflect the latest pipeline run.
(The Power BI project reads the warehouse directly; see scripts/build_powerbi.py.)"""
from __future__ import annotations

import json
import logging
from datetime import datetime

import pandas as pd
from scipy.stats import chi2_contingency

from src.config import path
from src.db import connect, read_sql

log = logging.getLogger(__name__)

ANALYSIS_QUERIES = ["executive_kpis", "segment_summary", "risk_by_group", "retention_budget_curve", "value_concentration",
                    "profit_sensitivity", "retention_cost_sensitivity"]


def run_analysis(conn) -> dict[str, pd.DataFrame]:
    out = path("reports/tables")
    out.mkdir(parents=True, exist_ok=True)
    results = {}
    for name in ANALYSIS_QUERIES:
        df = read_sql(path(f"sql/analysis/{name}.sql").read_text(encoding="utf-8"), conn)
        df.to_csv(out / f"analysis_{name}.csv", index=False)
        results[name] = df
    return results


def significance_checks(conn) -> dict:
    """Chi-square tests: are the descriptive differences between segments more than noise?"""
    c360 = read_sql("SELECT segment, limit_tier, sex, actual_default_oct::INT y FROM mart.customer_360", conn)
    out = {}
    for col in ["segment", "limit_tier", "sex"]:
        table = pd.crosstab(c360[col], c360.y)
        chi2, p, dof, _ = chi2_contingency(table)
        out[f"default_rate_by_{col}"] = {"chi2": float(chi2), "dof": int(dof), "p_value": float(p)}
    churn = read_sql("""SELECT s.segment, f.churn_label FROM features.churn_snapshots f
                        JOIN ml.customer_segments s USING (customer_id)
                        WHERE f.is_eligible AND f.snapshot_month_index = 4""", conn)
    chi2, p, dof, _ = chi2_contingency(pd.crosstab(churn.segment, churn.churn_label))
    out["dormancy_rate_by_segment_jul_snapshot"] = {"chi2": float(chi2), "dof": int(dof), "p_value": float(p)}
    return out


def write_dq_report(conn) -> None:
    run = read_sql("""SELECT * FROM audit.pipeline_runs WHERE status = 'loaded' ORDER BY run_id DESC LIMIT 1""", conn).iloc[0]
    checks = read_sql("SELECT * FROM audit.dq_check_results WHERE run_id = %s ORDER BY "
                      "CASE severity WHEN 'ERROR' THEN 1 WHEN 'WARN' THEN 2 ELSE 3 END, rows_failed DESC",
                      conn, (int(run.run_id),))
    status = read_sql("""SELECT month_index, status_code, count(*) n FROM core.fact_account_month
                         WHERE status_code BETWEEN -2 AND 3 GROUP BY 1, 2""", conn)
    pivot = status.pivot(index="status_code", columns="month_index", values="n").fillna(0).astype(int)
    pivot.columns = ["Apr", "May", "Jun", "Jul", "Aug", "Sep"]

    def fmt_row(r):
        pct = "" if pd.isna(r.pct_failed) else f"{r.pct_failed:.2f}%"
        return f"| `{r.check_name}` | {r.severity} | {r.rows_failed:,} | {pct} | {r.description} |"

    lines = [
        "# Data-quality report",
        "",
        f"_Generated by the pipeline on {datetime.now():%Y-%m-%d %H:%M} from `audit.dq_check_results` (run {int(run.run_id)})._",
        "",
        f"- Source file: `{run.source_file}` (SHA-256 `{run.file_sha256[:16]}...`)",
        f"- Rows read: {int(run.rows_read):,} | loaded to staging: {int(run.rows_loaded):,} | quarantined: {int(run.rows_rejected):,}",
        "",
        "ERROR checks send the row to `staging.rejected_rows`. WARN checks keep the row and record it in",
        "`audit.dq_row_flags`, because these are things a real portfolio contains (overpayments, over-limit",
        "balances) or coding issues I can work around. INFO checks are recorded for context only.",
        "",
        "| Check | Severity | Rows | % rows | What it means / how it's handled |",
        "|---|---|---:|---:|---|",
        *[fmt_row(r) for r in checks.itertuples()],
        "",
        "## Repayment-status coding changes in September",
        "",
        "Count of accounts by status code and month. Status 1 (one month late) is almost never used in",
        "Apr-Aug, where accounts move straight from 0 to 2, but it is common in September. I treat the",
        "September codes as not comparable with earlier months: month-to-month delinquency comparisons use",
        "60+ DPD (status >= 2), and the dormancy model only uses the 60+ DPD flag rather than raw codes.",
        "",
        "| Status | " + " | ".join(pivot.columns) + " |",
        "|---:|" + "---:|" * len(pivot.columns),
        *[f"| {idx} | " + " | ".join(f"{v:,}" for v in row) + " |" for idx, row in pivot.iterrows()],
        "",
        "## Other handling decisions",
        "",
        "- **Undocumented codes** (EDUCATION 0/5/6, MARRIAGE 0): kept the raw code and mapped the label to `Unknown`.",
        "- **Duplicate profiles**: rows identical except for ID are mostly never-used accounts with the same",
        "  limit and demographics. Different IDs plus plausible values -> kept as separate customers.",
        "- **Negative bills**: credit balances from overpayment. Kept; utilization can be negative.",
        "- **Over-limit balances**: kept; utilization can exceed 1 (interest and fees can push a balance over the limit).",
        "- **Credit limit**: reported once, so I assume it was constant over Apr-Sep 2005.",
        "",
    ]
    path("docs/data_quality_report.md").write_text("\n".join(lines), encoding="utf-8")


def run() -> None:
    with connect() as conn:
        analysis = run_analysis(conn)
        sig = significance_checks(conn)
        write_dq_report(conn)
    summary = {name: df.to_dict(orient="records") for name, df in analysis.items()
               if name in ("executive_kpis", "segment_summary", "risk_by_group", "profit_sensitivity",
                                "retention_cost_sensitivity")}
    summary["significance_tests"] = sig
    with open(path("reports/business_summary.json"), "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, default=float)
    log.info("export complete")
